### ISSUE TITLE
Crash when deploying into VPS

### ISSUE THREAD

**Issue by brianabdl** [mrismanaziz/Man-Userbot#176]
Log:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/Man-Userbot/userbot/__main__.py", line 49, in <module>
    LOOP.run_until_complete(autopilot())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/root/Man-Userbot/userbot/utils/utils.py", line 50, in autopilot
    heroku_var["BOTLOG_CHATID"] = grup_id
NameError: name 'heroku_var' is not defined
```

Seems like `heroku_var` in **utils.py** is causing this crash
https://github.com/mrismanaziz/Man-Userbot/blob/44e918435bcd7bc2a5de77d042591de98ce1e611/userbot/utils/utils.py#L50

**Comment by Vbs0089** [comment]
bruh read it enter loog chat id just add rose bot to ur chaat and make it admin and send /id to that channel and enter that id in above var

**Comment by brianabdl** [comment]
ah, yes, thankyou.
my mistake sir.
